os:
  - linux

language: go
go:
  - "1.15"

services:
  - docker

# define stages
stages:
  - build
  - integration-test

jobs:
  include:
    - stage: build
      name: "Build the image and run unit tests"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make build
          make build-images
          make push 

    - stage: integration-test 
      before_script:
        - source ./build/setup_kind.sh
        - echo $KUBECONFIG
      script: make test-integration
